mecanum_drive_controller:
  ros__parameters:
    type: "mecanum_drive_controller/MecanumDriveController"
    publish_rate: 50
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    wheel_separation: 0.25        
    wheel_base: 0.30            
    wheel_radius: 0.05           
    cmd_vel_timeout: 0.25
    use_stamped_vel: false

    left_front_wheel_names: ["front_left_wheel_joint"]
    right_front_wheel_names: ["front_right_wheel_joint"]
    left_rear_wheel_names: ["rear_left_wheel_joint"]
    right_rear_wheel_names: ["rear_right_wheel_joint"]
