planner_server:
  ros__parameters:
    planner_plugins: ["NavfnPlanner"]
    NavfnPlanner:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      autostart: true

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_follow_path_controller::FollowPath"
      autostart: true
