planner_server:
  ros__parameters:
    planner_plugins: ["NavFnPlanner"]
    NavFnPlanner:
      plugin: "nav2_navfn_planner/NavfnPlanner"
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_follow_path_controller/FollowPath"
