planner_server:
  ros__parameters:
    planner_plugins: ["NavfnPlanner"]
    NavfnPlanner:
      plugin: "nav2_navfn_planner::NavfnPlanner"
bt_navigator:
  ros__parameters:
    planner_id: "NavfnPlanner"
    default_bt_xml_filename: "navigate_to_pose_w_replanning_and_recovery.xml"
controller_server:
  ros__parameters:
    controller_plugins: ["DWBLocalPlanner"]
    DWBLocalPlanner:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      critics:
        - "RotateToGoal"
        - "PathAlign"
        - "GoalAlign"
        - "PathDist"
        - "GoalDist"
      RotateToGoal:
        critic_name: "dwb_critics::RotateToGoalCritic"
        xy_goal_tolerance: 0.25
        yaw_goal_tolerance: 0.25
      PathAlign:
        critic_name: "dwb_critics::PathAlignCritic"
        scale: 32.0
      GoalAlign:
        critic_name: "dwb_critics::GoalAlignCritic"
        scale: 24.0 
      PathDist:
        critic_name: "dwb_critics::PathDistCritic"
        scale: 32.0
      GoalDist:
        critic_name: "dwb_critics::GoalDistCritic"
        scale: 24.0

behavior_server:
  ros__parameters:
    use_sim_time: False
    costmap_topic: /local_costmap/costmap
    footprint_topic: /local_costmap/published_footprint
    behaviors: ["spin", "backup", "wait"]  
    spin:
      action_name: "spin"

local_costmap:
  ros__parameters:
    use_sim_time: False
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
    inflation_layer:
      inflation_radius: 0.55