planner_server:
  ros__parameters:
    planner_plugins: ["NavfnPlanner"]
    NavfnPlanner:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      autostart: true

controller_server:
  ros__parameters:
    controller_plugins: ["DWBLocalPlanner"]
    DWBLocalPlanner:
      plugin: "dwb_core::DWBLocalPlanner"
      autostart: true
