slam_toolbox:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    laser_frame: lidar_link
    mode: mapping                  
    transform_tolerance: 0.2          
    max_laser_scan_queue_size: 50     
    max_laser_range: 8.0              
    minimum_time_interval: 0.05       
    resolution: 0.05                  
    publish_period_sec: 0.5           
    map_update_interval_sec: 0.2      
    optimize_every_n_nodes: 10
    max_likelihood_score: 0.7
    scan_topic: /scan                 
    odom_topic: /odom                 
    provide_odom_frame: true
    use_scan_matching: true
    odom0_config: [false, false, false, false, false, false]