# diff_drive_controller:
#   type: "diff_drive_controller/DiffDriveController"
#   left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
#   right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
#   wheel_separation: 0.5  # distance between left and right wheels (meters)
#   wheel_radius: 0.1      # radius of wheels (meters)
#   cmd_vel_timeout: 0.5
#   publish_rate: 50
#   use_stamped_vel: false
